---
default_stages:
  - pre-commit
  - pre-push
  - manual

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.1
    hooks:
      - id: yamlfmt
