---
substitutions:
  name: bedroomtemp
  sensor_location: Bedroom
  ip: '103'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

sensor:
  - <<: !include common/temperature_sensor_dht22.yaml
