---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: bedroomtemp
  sensor_location: Bedroom
  api_timeout: '60'

packages:
  <<: !include_dir_named packages
  board: !include common/esp8266.yaml
  pmsx003: !include common/pmsx003.yaml
  dht22: !include {file: common/temperature_sensor_dht22.yaml, vars: {temperature_offset: '0.0', update_interval: '60'}}

uart:
  tx_pin: D6
  rx_pin: D7
  baud_rate: 9600

switch:
  - platform: gpio
    pin:
      number: D3
    id: pms_set
    name: 'Start measuring'

interval:
  - interval: 300s
    then:
      - switch.turn_on: pms_set
      - delay: 30s
      - switch.turn_off: pms_set
