---
substitutions:
  name: bedroomtemp
  sensor_location: Bedroom
  ip: '103'
  temp_update_seconds: '60'
  temperature_offset: '0.0'
  api_timeout: '60'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

uart:
  tx_pin: D6
  rx_pin: D7
  baud_rate: 9600

sensor:
  - <<: !include common/pmsx003.yaml
  - <<: !include common/temperature_sensor_dht22.yaml

switch:
  - platform: gpio
    pin:
      number: D3
    id: pms_set
    name: 'Start measuring'

interval:
  - interval: 300s
    then:
      - switch.turn_on: pms_set
      - delay: 30s
      - switch.turn_off: pms_set
