---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: bedroomtemp
  sensor_location: Bedroom
  api_timeout: '60'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

uart:
  tx_pin: D6
  rx_pin: D7
  baud_rate: 9600

sensor:
  - <<: !include common/pmsx003.yaml
  - <<: !include { file: common/temperature_sensor_dht22.yaml, vars: {temperature_offset: '0.0', update_interval: '60'} }

switch:
  - platform: gpio
    pin:
      number: D3
    id: pms_set
    name: 'Start measuring'

interval:
  - interval: 300s
    then:
      - switch.turn_on: pms_set
      - delay: 30s
      - switch.turn_off: pms_set
