---
substitutions:
  name: connoralarm
  sensor_location: "Connor's Room"
  api_timeout: '0'
  page_display_time: '15s'

packages:
  <<: !include_dir_named packages
  board: !include common/ulanzi_tc001.yaml
  alarm: !include common/rtttl-song-alarm.yaml
