---
# vim: filetype=esphome:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell
substitutions:
  name: connoralarm
  sensor_location: "Connor's Room"
  ip: '113'
  api_timeout: '0'

packages:
  <<: !include_dir_named packages
  board: !include common/esp8266.yaml
  clock: !include common/tm1637-clock.yaml
  alarm: !include common/rtttl-song-alarm.yaml
