---
substitutions:
  name: connortemp
  sensor_location: "Connor's Room"
  ip: '101'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

sensor:
  - <<: !include common/temperature_sensor_dht22.yaml
