---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: kitchenvoc
  sensor_location: Kitchen
  api_timeout: '600'

<<: !include common/esp32.yaml

packages:
  <<: !include_dir_named packages
  sgp30: !include {file: common/sgp30.yaml, vars: {i2c_bus: bus_a}}
  bme680: !include {file: common/bme680_bsec.yaml, vars: {temperature_offset: 0.0, i2c_address: 0x77, i2c_bus: bus_b}}

i2c:
  - id: bus_a
    scl: GPIO15
    sda: GPIO2
  - id: bus_b
    scl: GPIO23
    sda: GPIO22
