---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: livingroomtemp
  sensor_location: 'Living Room'
  api_timeout: '600'

packages:
  <<: !include_dir_named packages
  board: !include common/esp8266.yaml
  dht22: !include {file: common/temperature_sensor_dht22.yaml, vars: {temperature_offset: '0.0', update_interval: '15'}}
