---
# vim: filetype=esphome:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell
substitutions:
  name: livingroomtemp
  sensor_location: 'Living Room'
  temperature_offset: '0.0'
  temp_update_seconds: '15'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

sensor:
  - <<: !include common/temperature_sensor_dht22.yaml
