---
substitutions:
  name: livingroomtemp
  sensor_location: 'Living Room'
  ip: '106'
  temperature_offset: '0.0'
  temp_update_seconds: '15'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

sensor:
  - <<: !include common/temperature_sensor_dht22.yaml
