---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: office
  sensor_location: Office
  api_timeout: '600'

<<:
  - !include common/esp32.yaml
  - !include { file: common/sgp30.yaml, vars: {i2c_bus: bus_a} }
  - !include { file: common/bme680_bsec.yaml, vars: {temperature_offset: 0.0, i2c_address: 0x77, i2c_bus: bus_b} }

packages: !include_dir_named packages

i2c:
  - id: bus_a
    scl: GPIO17
    sda: GPIO16
  - id: bus_b
    scl: GPIO23
    sda: GPIO22
