---
substitutions:
  name: olivetemp
  sensor_location: "Olive's Room"
  ip: '102'
  temp_update_seconds: '60'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

sensor:
  - <<: !include common/temperature_sensor_dht22.yaml
