---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: olivetemp
  sensor_location: "Olive's Room"
  api_timeout: '60'

packages:
  <<: !include_dir_named packages
  board: !include common/esp8266.yaml
  dht22: !include {file: common/temperature_sensor_dht22.yaml, vars: {temperature_offset: '0.0', update_interval: '60'}}
