---
substitutions:
  name: olivealarm
  sensor_location: "Olive's Room"
  ip: '114'
  api_timeout: '600'

<<:
  - !include common/esp8266.yaml
  - !include common/max7219-matrix-clock.yaml
  - !include common/rtttl-song-alarm.yaml

packages: !include_dir_named packages
