---
# vim: filetype=esphome:syntax=yaml:
substitutions:
  name: wiringtemp
  sensor_location: Wiring Closet
  temp_update_seconds: '60'
  temperature_offset: '0.0'
  api_timeout: '60'

<<: !include common/esp8266.yaml

packages: !include_dir_named packages

sensor:
  - <<: !include common/temperature_sensor_dht22.yaml
