---
esphome:
  name: ${name}
  build_path: build/${name}
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    - wait_until:
        condition:
          api.connected:
    - logger.log: 'API Connected, starting sleep script'
    - script.execute: consider_deep_sleep

binary_sensor:
  - platform: homeassistant
    id: prevent_deep_sleep
    name: Prevent Deep Sleep
    entity_id: input_boolean.prevent_deep_sleep

script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - delay: ${sleep_delay_seconds}s
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - logger.log: 'Skipping sleep'
            - deep_sleep.prevent: deep_sleep_control
          else:
            - logger.log: 'Entering sleep'
            - deep_sleep.enter: deep_sleep_control
      - script.execute: consider_deep_sleep

deep_sleep:
  id: deep_sleep_control
  sleep_duration: ${sleep_seconds}s
