---
# vim: filetype=esphome:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell
binary_sensor:
  - platform: gpio
    name: ${sensor_location} Vibration Sensor
    pin:
      number: D7
      mode: INPUT
    device_class: vibration
    filters:
      - delayed_off: 15s
