---
# vim: filetype=esphome:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell
esphome:
  name: ${name}
  build_path: build/${name}
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
  id: m5_main_bus
  sda: GPIO21
  scl: GPIO22
  scan: true

output:
  - platform: ledc
    pin:
      number: GPIO10
      inverted: true
    id: builtin_led
  - platform: ledc
    pin:
      number: GPIO2
    id: buzzer

sensor:
  - platform: axp192
    address: 0x34
    i2c_id: m5_main_bus
    update_interval: 30s
    battery_level:
      name: ${sensor_location} Battery Level
      id: "${name}_batterylevel"
