---
# Note: This requires a uart section similar to the following:
# uart:
#   tx_pin: D6
#   rx_pin: D7
#   baud_rate: 9600

- platform: pmsx003
  type: PMSX003
  pm_1_0:
    name: "Particulate Matter <1.0µm Concentration"
  pm_2_5:
    name: "Particulate Matter <2.5µm Concentration"
  pm_10_0:
    name: "Particulate Matter <10.0µm Concentration"
