---
# vim: filetype=esphome:syntax=yaml:ts=2:sts=2:sw=2:expandtab:autoindent:nospell
- platform: dht
  model: DHT22
  pin: D2
  temperature:
    name: '${sensor_location} Temperature'
    id: '${name}_temperature_sensor'
    filters:
      - offset: '${temperature_offset}'
      - median:
          window_size: 7
          send_every: 5
          send_first_at: 3
  humidity:
    name: '${sensor_location} Humidity'
    id: '${name}_humidity_sensor'
    filters:
      - median:
          window_size: 7
          send_every: 5
          send_first_at: 3
  update_interval: '${temp_update_seconds}s'
  id: '${name}_sensor'
