---
- platform: dht
  model: DHT22
  pin: D2
  temperature:
    name: '${sensor_location} Temperature'
    on_value:
      if:
        condition:
          api.connected:
        then:
          - homeassistant.service:
              service: input_number.set_value
              data:
                entity_id: input_number.${name}_temperature
              variables:
                temp: |-
                  return esphome::to_string(x);
              data_template:
                value: '{{ temp }}'
  humidity:
    name: '${sensor_location} Humidity'
    on_value:
      if:
        condition:
          api.connected:
        then:
          - homeassistant.service:
              service: input_number.set_value
              data:
                entity_id: input_number.${name}_humidity
              variables:
                humidity: |-
                  return esphome::to_string(x);
              data_template:
                value: '{{ humidity }}'
  update_interval: '${temp_update_seconds}s'
  id: '${name}_sensor'
