---
- platform: dht
  model: DHT22
  pin: D2
  temperature:
    name: '${sensor_location} Temperature'
  humidity:
    name: '${sensor_location} Humidity'
  update_interval: '${temp_update_seconds}s'
  id: '${name}_sensor'
