---
# vim: filetype=esphome:syntax=yaml:
wifi:
  networks: !secret networks

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name} Fallback
    password: !secret fallback_psk

sensor:
  - platform: wifi_signal
    name: '${name} WiFi Signal'
    id: '${name}_wifi_db'
    entity_category: 'diagnostic'

  - platform: copy
    source_id: '${name}_wifi_db'
    name: '${name} WiFi Signal Percent'
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: '%'
    entity_category: 'diagnostic'

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${name} IP Address
      entity_category: 'diagnostic'
    mac_address:
      name: ${name} MAC Address
      entity_category: 'diagnostic'
