---
name: ESPHome CI

'on':
  push:

jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: ansible-actions/yamllint-action@v0.0.2
        with:
          target: './'
  esphome:
    runs-on: ubuntu-latest
    needs:
      - yaml_lint
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install esphome
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./
      - name: Run esphome on all files
        run: |
          for f in $(find . -maxdepth 1 -type f -name "*.yaml" -not -name "secrets.yaml" -not -name ".*.yaml"); do
            esphome config "${f}"
          done
